import 'package:dio/dio.dart' show Options;
import 'package:stylemint_mobile_frontend/core/network/api_client.dart';
import 'package:stylemint_mobile_frontend/features/creator/reels/data/models/creator_reel_detail_dto.dart';
import 'package:stylemint_mobile_frontend/features/creator/reels/data/models/creator_reel_summary_dto.dart';

/// One page of the creator's own reels, plus the total across all pages.
class CreatorReelsPage {
  const CreatorReelsPage({required this.items, required this.totalCount});

  final List<CreatorReelSummaryDto> items;
  final int totalCount;
}

class CreatorReelsRemoteDataSource {
  CreatorReelsRemoteDataSource({required this.apiClient});

  final ApiClient apiClient;

  Future<CreatorReelDetailDto> getReelDetail(String reelId) async {
    final response = await apiClient.get('/v1/creator/reels/$reelId');
    return CreatorReelDetailDto.fromJson(response as Map<String, dynamic>);
  }

  /// `GET /v1/creator/reels` — the creator's own reels, drafts included.
  ///
  /// The endpoint takes `cursor` and `pageSize`; it has no `sortBy`/`order`
  /// and no `limit`. Those were being sent and silently ignored, so a request
  /// for 6 reels "newest first" came back as the server's default page in
  /// cursor order. [pageSize] is the real parameter.
  Future<CreatorReelsPage> listCreatorReels({int pageSize = 6}) async {
    final response = await apiClient.get(
      '/v1/creator/reels',
      queryParameters: {'pageSize': pageSize},
    );
    final body = response as Map<String, dynamic>? ?? const {};
    final items = (body['items'] as List<dynamic>? ?? const [])
        .whereType<Map<String, dynamic>>()
        .map(CreatorReelSummaryDto.fromJson)
        .toList(growable: false);
    return CreatorReelsPage(
      items: items,
      // The creator's true reel total, across every page — not the length of
      // whatever this page happened to return.
      totalCount: (body['totalCount'] as num?)?.toInt() ?? items.length,
    );
  }

  Future<void> publishReel(String reelId, String idempotencyKey) async {
    await apiClient.post(
      '/v1/creator/reels/$reelId/publish',
      data: <String, dynamic>{},
      options: Options(
        headers: {
          'requiresToken': true,
          'Idempotency-Key': idempotencyKey,
        },
      ),
    );
  }

  Future<void> unpublishReel(String reelId, String idempotencyKey) async {
    await apiClient.post(
      '/v1/creator/reels/$reelId/unpublish',
      data: <String, dynamic>{},
      options: Options(
        headers: {
          'requiresToken': true,
          'Idempotency-Key': idempotencyKey,
        },
      ),
    );
  }

  // PUT /v1/creator/reels/{reelId}/caption — null/blank clears the caption.
  Future<void> updateCaption(
    String reelId,
    String? caption,
    String idempotencyKey,
  ) async {
    await apiClient.put(
      '/v1/creator/reels/$reelId/caption',
      data: <String, dynamic>{'caption': caption},
      options: Options(
        headers: {
          'requiresToken': true,
          'Idempotency-Key': idempotencyKey,
        },
      ),
    );
  }

  Future<List<ReelTagManagementDto>> listTaggedProducts(String reelId) async {
    final response = await apiClient.get(
      '/v1/creator/reels/$reelId/tagged-products',
    );
    return (response as List<dynamic>? ?? const <dynamic>[])
        .map(
          (e) => ReelTagManagementDto.fromJson(e as Map<String, dynamic>),
        )
        .toList(growable: false);
  }

  Future<ReelTagManagementDto> tagProduct(
    String reelId, {
    required String productId,
    required double overlayPositionX,
    required double overlayPositionY,
    required String idempotencyKey,
  }) async {
    final response = await apiClient.post(
      '/v1/creator/reels/$reelId/tagged-products',
      data: {
        'productId': productId,
        'overlayPositionX': overlayPositionX,
        'overlayPositionY': overlayPositionY,
      },
      options: Options(
        headers: {
          'requiresToken': true,
          'Idempotency-Key': idempotencyKey,
        },
      ),
    );
    return ReelTagManagementDto.fromJson(response as Map<String, dynamic>);
  }

  Future<void> untagProduct(
    String reelId,
    String taggedProductId,
    String idempotencyKey,
  ) async {
    await apiClient.authDelete(
      '/v1/creator/reels/$reelId/tagged-products/$taggedProductId',
      options: Options(
        headers: {
          'requiresToken': true,
          'Idempotency-Key': idempotencyKey,
        },
      ),
    );
  }

  // DELETE /v1/creator/reels/{reelId}
  Future<void> deleteReel(String reelId, String idempotencyKey) async {
    await apiClient.authDelete(
      '/v1/creator/reels/$reelId',
      options: Options(
        headers: {
          'requiresToken': true,
          'Idempotency-Key': idempotencyKey,
        },
      ),
    );
  }

  // GET /v1/creator/reels/{reelId}/post-publish-report
  // Returns the 24h post-publish coaching report generated by Creator Studio.
  Future<Map<String, dynamic>> getPostPublishReport(String reelId) async {
    final response = await apiClient.get(
      '/v1/creator/reels/$reelId/post-publish-report',
    );
    return response as Map<String, dynamic>;
  }
}
