import 'package:stylemint_mobile_frontend/features/customer/reels/domain/entities/reel.dart';
import 'package:stylemint_mobile_frontend/shared/domain/entities/money.dart';

// Free HTTPS MP4s from stable public CDNs (Flutter's assets-for-api-docs,
// media.w3.org, Blender) — no auth required. (The old gtv-videos-bucket
// sample URLs now return 403 and were replaced.)
final kMockReels = <Reel>[
  Reel(
    id: 'reel_001',
    sourceUrl: 'https://www.youtube.com/shorts/K4TOrB4TTSg',
    thumbnailUrl: 'https://picsum.photos/seed/stylemint-reel1/400/700',
    videoUrl:
        'https://flutter.github.io/assets-for-api-docs/assets/videos/butterfly.mp4',
    creatorId: 'u_002',
    creatorName: 'Nina Bloom',
    creatorAvatarUrl: '',
    caption:
        'Winter skincare routine that actually works ✨ My top 3 picks for dry skin this season 🌿 #skincare #winterroutine #cleanbeauty',
    musicTitle: 'Golden Hour',
    musicArtist: 'JVKE',
    taggedProducts: [
      TaggedProductEntity(
        id: 'p_sk01',
        name: 'Hydra Boost Serum',
        imageUrl: 'https://picsum.photos/seed/serum01/80/80',
        price: const Money(amount: 1299, currency: 'NPR'),
        quantity: 12,
      ),
      TaggedProductEntity(
        id: 'p_sk02',
        name: 'Vitamin C Moisturiser',
        imageUrl: 'https://picsum.photos/seed/moisturiser01/80/80',
        price: const Money(amount: 899, currency: 'NPR'),
        quantity: 5,
      ),
    ],
    likeCount: 48200,
    commentCount: 312,
    shareCount: 890,
    createdAt: DateTime(2024, 6, 20),
    isLikedByUser: false,
    isWishlistedByUser: false,
    isCreatorFollowed: true,
  ),
  Reel(
    id: 'reel_002',
    sourceUrl: 'https://www.youtube.com/shorts/Ct3lR1sUhwA',
    thumbnailUrl: 'https://picsum.photos/seed/stylemint-reel2/400/700',
    videoUrl:
        'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4',
    creatorId: 'u_001',
    creatorName: 'Maya Lume',
    creatorAvatarUrl: '',
    caption:
        'GRWM for a coffee date 🤎 Quiet luxury vibes all the way — minimal, clean, effortless. #ootd #grwm #quietluxury #fashiontips',
    musicTitle: 'Espresso',
    musicArtist: 'Sabrina Carpenter',
    taggedProducts: [
      TaggedProductEntity(
        id: 'p_fa01',
        name: 'Linen Blazer – Cream',
        imageUrl: 'https://picsum.photos/seed/blazer01/80/80',
        price: const Money(amount: 2499, currency: 'NPR'),
        quantity: 8,
      ),
    ],
    likeCount: 93700,
    commentCount: 1204,
    shareCount: 3500,
    createdAt: DateTime(2024, 6, 18),
    isLikedByUser: true,
    isWishlistedByUser: true,
    isCreatorFollowed: true,
  ),
  Reel(
    id: 'reel_003',
    sourceUrl: 'https://www.youtube.com/shorts/q4LOvgAGX8g',
    thumbnailUrl: 'https://picsum.photos/seed/stylemint-reel3/400/700',
    videoUrl:
        'https://media.w3.org/2010/05/sintel/trailer.mp4',
    creatorId: 'u_005',
    creatorName: 'Theo Run',
    creatorAvatarUrl: '',
    caption:
        '5 AM workout gear that changed my mornings 💪 Lightweight, breathable, no excuses. #fitness #activewear #morningroutine',
    musicTitle: 'Levitating',
    musicArtist: 'Dua Lipa',
    taggedProducts: [
      TaggedProductEntity(
        id: 'p_fi01',
        name: 'Performance Dry-Fit Tee',
        imageUrl: 'https://picsum.photos/seed/tee01/80/80',
        price: const Money(amount: 799, currency: 'NPR'),
        quantity: 20,
      ),
      TaggedProductEntity(
        id: 'p_fi02',
        name: 'Flex Shorts – Black',
        imageUrl: 'https://picsum.photos/seed/shorts01/80/80',
        price: const Money(amount: 1099, currency: 'NPR'),
        quantity: 14,
      ),
    ],
    likeCount: 21500,
    commentCount: 198,
    shareCount: 440,
    createdAt: DateTime(2024, 6, 15),
    isLikedByUser: false,
    isWishlistedByUser: false,
    isCreatorFollowed: true,
  ),
  Reel(
    id: 'reel_004',
    sourceUrl: 'https://www.youtube.com/shorts/IfMpGlHvpTM',
    thumbnailUrl: 'https://picsum.photos/seed/stylemint-reel4/400/700',
    videoUrl:
        'https://media.w3.org/2010/05/bunny/trailer.mp4',
    creatorId: 'u_004',
    creatorName: 'Shree Teen',
    creatorAvatarUrl: '',
    caption:
        'Packing for Bali 🌴 Everything fits in a carry-on — here\'s exactly what I\'m bringing. #traveloutfit #packingwithme #ootd',
    musicTitle: 'Watermelon Sugar',
    musicArtist: 'Harry Styles',
    taggedProducts: [
      TaggedProductEntity(
        id: 'p_tr01',
        name: 'Oversized Linen Shirt',
        imageUrl: 'https://picsum.photos/seed/linen01/80/80',
        price: const Money(amount: 1599, currency: 'NPR'),
        quantity: 7,
      ),
    ],
    likeCount: 61000,
    commentCount: 724,
    shareCount: 2100,
    createdAt: DateTime(2024, 6, 12),
    isLikedByUser: false,
    isWishlistedByUser: true,
    isCreatorFollowed: true,
  ),
  Reel(
    id: 'reel_005',
    sourceUrl: 'https://www.youtube.com/shorts/BVBsXMbsC4o',
    thumbnailUrl: 'https://picsum.photos/seed/stylemint-reel5/400/700',
    videoUrl:
        'https://media.w3.org/2010/05/video/movie_300.mp4',
    creatorId: 'u_006',
    creatorName: 'Lena Styles',
    creatorAvatarUrl: '',
    caption:
        'Street style inspo from the city 🏙️ Three outfits, zero filters, all attitude. #streetstyle #fashion #streetwear',
    musicTitle: 'Blinding Lights',
    musicArtist: 'The Weeknd',
    taggedProducts: [
      TaggedProductEntity(
        id: 'p_ss01',
        name: 'Cargo Pants – Olive',
        imageUrl: 'https://picsum.photos/seed/cargo01/80/80',
        price: const Money(amount: 1899, currency: 'NPR'),
        quantity: 9,
      ),
      TaggedProductEntity(
        id: 'p_ss02',
        name: 'Graphic Tee – Black',
        imageUrl: 'https://picsum.photos/seed/graphictee01/80/80',
        price: const Money(amount: 699, currency: 'NPR'),
        quantity: 25,
      ),
    ],
    likeCount: 112000,
    commentCount: 2341,
    shareCount: 6700,
    createdAt: DateTime(2024, 6, 10),
    isLikedByUser: true,
    isWishlistedByUser: false,
    isCreatorFollowed: false,
  ),
  Reel(
    id: 'reel_006',
    sourceUrl: 'https://www.youtube.com/shorts/Px_EHgW4y9k',
    thumbnailUrl: 'https://picsum.photos/seed/stylemint-reel6/400/700',
    videoUrl:
        'https://download.blender.org/peach/bigbuckbunny_movies/BigBuckBunny_320x180.mp4',
    creatorId: 'u_003',
    creatorName: 'Ravi Kit',
    creatorAvatarUrl: '',
    caption:
        'Best budget tech accessories under NPR 2000 🔥 Honest review, no sponsors. #techreview #gadgets #budgettech',
    musicTitle: 'Stay',
    musicArtist: 'The Kid LAROI & Justin Bieber',
    taggedProducts: [
      TaggedProductEntity(
        id: 'p_te01',
        name: 'Magnetic Phone Mount',
        imageUrl: 'https://picsum.photos/seed/mount01/80/80',
        price: const Money(amount: 499, currency: 'NPR'),
        quantity: 30,
      ),
    ],
    likeCount: 38900,
    commentCount: 567,
    shareCount: 1200,
    createdAt: DateTime(2024, 6, 8),
    isLikedByUser: false,
    isWishlistedByUser: false,
    isCreatorFollowed: true,
  ),
];
