import 'package:stylemint_mobile_frontend/features/profile/domain/entities/following_user.dart';

const kMockFollowingUsers = <FollowingUser>[
  FollowingUser(
    id: 'u_001',
    displayName: 'Maya Lume',
    avatarUrl: '',
    handle: 'maya.lume',
    isFollowing: true,
    followerCount: 128400,
    category: 'Fashion & Lifestyle',
    bio: 'Daily fits, styling hacks and the latest drops curated for you.',
  ),
  FollowingUser(
    id: 'u_002',
    displayName: 'Nina Bloom',
    avatarUrl: '',
    handle: 'ninabloom',
    isFollowing: true,
    followerCount: 203000,
    category: 'Beauty & Skincare',
    bio: 'Clean beauty routines and product breakdowns for every skin type.',
  ),
  FollowingUser(
    id: 'u_003',
    displayName: 'Ravi Kit',
    avatarUrl: '',
    handle: 'ravikit',
    isFollowing: true,
    followerCount: 87100,
    category: 'Tech & Gadgets',
    bio: 'Hands-on reviews and honest takes on the gear worth your money.',
  ),
  FollowingUser(
    id: 'u_004',
    displayName: 'Shree Teen',
    avatarUrl: '',
    handle: 'alieen.ace43',
    isFollowing: true,
    followerCount: 52300,
    category: 'Travel & Skincare',
    bio: 'Get personalised recommendations from creators in Fashion, Beauty, and Fitness.',
  ),
  FollowingUser(
    id: 'u_005',
    displayName: 'Theo Run',
    avatarUrl: '',
    handle: 'theoruns',
    isFollowing: true,
    followerCount: 64800,
    category: 'Fitness & Wellness',
    bio: 'Workouts, recovery tips and gear to keep you moving every day.',
  ),
  FollowingUser(
    id: 'u_006',
    displayName: 'Lena Styles',
    avatarUrl: '',
    handle: 'lenastyles',
    isFollowing: true,
    followerCount: 310000,
    category: 'Street Style',
    bio: 'Street fashion straight from the city — no filters, just looks.',
  ),
];
